export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_ACTIVE_FIRESTORE_DETAILS = "SET_ACTIVE_FIRESTORE_DETAILS";

export const SET_UPDATE_LINKED_ACCOUNTS = "SET_UPDATE_LINKED_ACCOUNTS";